CREATE DATABASE chirpy;
USE chirpy;

CREATE TABLE `chirps` (
  -- TABLE CODE TO GO HERE
id Int(11) AUTO_INCREMENT NOT NULL,
author VARCHAR(225) NOT NULL,
body VARCHAR(255) NOT NULL,,
create_at DATETIME NOT NULL,
PRIMARY KEY(id));
